# Generated by Django 3.0.1 on 2019-12-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=9)),
                ('status', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agencies',
                'db_table': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='AgentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AgentMaster',
                'verbose_name_plural': 'AgentMasters',
                'db_table': 'AgentMaster',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'PhoneType',
                'verbose_name_plural': 'PhoneTypes',
                'db_table': 'PhoneType',
            },
        ),
        migrations.CreateModel(
            name='AgentPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipsadmin.Agent')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipsadmin.PhoneType')),
            ],
            options={
                'verbose_name': 'AgentPhone',
                'verbose_name_plural': 'AgentPhones',
                'db_table': 'AgentPhone',
            },
        ),
        migrations.CreateModel(
            name='AgentEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('get_portal_email', models.BooleanField(default=True)),
                ('agent_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipsadmin.Agent')),
            ],
            options={
                'verbose_name': 'AgentEmail',
                'verbose_name_plural': 'AgentEmails',
                'db_table': 'AgentEmail',
            },
        ),
        migrations.CreateModel(
            name='AgentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=9)),
                ('agent_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipsadmin.Agent')),
            ],
            options={
                'verbose_name': 'AgentAddress',
                'verbose_name_plural': 'AgentAddresses',
                'db_table': 'AgentAddress',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_master_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagents', to='scipsadmin.AgentMaster'),
        ),
    ]
